[toml-schema]
version = 2

[title] 
type="string"
minlength=10
maxlength=20

[owner] 
type="table"

	[owner.name]
	type="string"

	[owner.dob]
	type="local-date"

[database]
type="table"

	[database.server]
	type="string"

	[database.ports]
	type="array"
	arraytype="integer"

	[database.connection_max]
	type="integer"

	[database.enabled]
	type="boolean"
	optional=true
	default=false

[servers]
type="table-sequence"

	[servers.ip]
	type="string"

	[servers.dc]
	type="string"

[clients]
type="table"

	[clients.data]
	type="array"

[hosts]
type="array"
