;; TOML Schema Definition (TOSD) grammar layer
;; Author: Bruno Borges
;;
;; TOSD files are TOML 1.0 documents. This ABNF defines the schema vocabulary
;; and document shape layered on top of TOML; TOML 1.0 remains authoritative for
;; base key, table, array, inline-table, string, number, boolean, and date/time
;; syntax.

toml-schema-document = toml-schema-table [ types-table ] elements-table

toml-schema-table = toml-table-header-toml-schema version [ metadata-table ]
types-table       = toml-table-header-types *schema-definition
elements-table    = toml-table-header-elements 1*schema-definition
metadata-table    = toml-table-header-toml-schema-meta *toml-keyval

schema-definition = schema-definition-table *definition-property [ children-table ]
children-table    = schema-children-table *children-entry
children-entry    = toml-key keyval-sep toml-inline-table

schema-key = type / typeof / typeref / arraytype / itemtype / oneof / anyof
           / allowedvalues / pattern / optional / default / min / max
           / minlength / maxlength / minoccurs / maxoccurs / children

definition-property = type / typeof / typeref / arraytype / itemtype / oneof / anyof
                    / allowedvalues / pattern / optional / default / min / max
                    / minlength / maxlength / minoccurs / maxoccurs

version       = "version" keyval-sep toml-string
type          = "type" keyval-sep built-in-type
typeof        = "typeof" keyval-sep toml-string
typeref       = "typeref" keyval-sep toml-string       ; legacy alias for typeof
arraytype     = "arraytype" keyval-sep array-built-in-type
itemtype      = "itemtype" keyval-sep toml-string
oneof         = "oneof" keyval-sep toml-array
anyof         = "anyof" keyval-sep toml-array
allowedvalues = "allowedvalues" keyval-sep toml-array
pattern       = "pattern" keyval-sep toml-string
optional      = "optional" keyval-sep toml-boolean
default       = "default" keyval-sep toml-value
min           = "min" keyval-sep toml-value
max           = "max" keyval-sep toml-value
minlength     = "minlength" keyval-sep toml-integer
maxlength     = "maxlength" keyval-sep toml-integer
minoccurs     = "minoccurs" keyval-sep toml-integer    ; legacy alias for minlength
maxoccurs     = "maxoccurs" keyval-sep toml-integer    ; legacy alias for maxlength
children      = "children"

built-in-type = anytype / stringtype / integertype / floattype / booleantype
              / offsetdatetimetype / localdatetimetype / localdatetype / localtimetype
              / arraytype-name / tabletype / collectiontype / tablecollectiontype

array-built-in-type = anytype / stringtype / integertype / floattype / booleantype
                    / offsetdatetimetype / localdatetimetype / localdatetype / localtimetype
                    / arraytype-name / tabletype

anytype             = DQUOTE %x61.6e.79 DQUOTE                                      ; "any"
stringtype          = DQUOTE %x73.74.72.69.6e.67 DQUOTE                             ; "string"
integertype         = DQUOTE %x69.6e.74.65.67.65.72 DQUOTE                          ; "integer"
floattype           = DQUOTE %x66.6c.6f.61.74 DQUOTE                                ; "float"
booleantype         = DQUOTE %x62.6f.6f.6c.65.61.6e DQUOTE                          ; "boolean"
offsetdatetimetype  = DQUOTE %x6f.66.66.73.65.74.2d.64.61.74.65.2d.74.69.6d.65 DQUOTE ; "offset-date-time"
localdatetimetype   = DQUOTE %x6c.6f.63.61.6c.2d.64.61.74.65.2d.74.69.6d.65 DQUOTE    ; "local-date-time"
localdatetype       = DQUOTE %x6c.6f.63.61.6c.2d.64.61.74.65 DQUOTE                   ; "local-date"
localtimetype       = DQUOTE %x6c.6f.63.61.6c.2d.74.69.6d.65 DQUOTE                   ; "local-time"
arraytype-name      = DQUOTE %x61.72.72.61.79 DQUOTE                                  ; "array"
tabletype           = DQUOTE %x74.61.62.6c.65 DQUOTE                                  ; "table"
collectiontype      = DQUOTE %x63.6f.6c.6c.65.63.74.69.6f.6e DQUOTE                   ; "collection"
tablecollectiontype = DQUOTE %x74.61.62.6c.65.2d.63.6f.6c.6c.65.63.74.69.6f.6e DQUOTE ; "table-collection"

;; TOML 1.0 grammar terminals used by TOSD.

toml-table-header-toml-schema      = <TOML 1.0 table header for [toml-schema]>
toml-table-header-types            = <TOML 1.0 table header for [types]>
toml-table-header-elements         = <TOML 1.0 table header for [elements]>
toml-table-header-toml-schema-meta = <TOML 1.0 table header under [toml-schema.meta]>
schema-definition-table            = <TOML 1.0 table header under [types] or [elements]>
schema-children-table              = <TOML 1.0 table header named children under a schema definition>
toml-keyval                        = <TOML 1.0 key/value pair>
toml-key                           = <TOML 1.0 key>
toml-value                         = <TOML 1.0 value>
toml-string                        = <TOML 1.0 string>
toml-array                         = <TOML 1.0 array>
toml-inline-table                  = <TOML 1.0 inline table>
toml-boolean                       = <TOML 1.0 boolean>
toml-integer                       = <TOML 1.0 integer>

keyval-sep = *WSP "=" *WSP

;; Built-in ABNF terms, reproduced here for clarity.

DQUOTE = %x22
WSP = SP / HTAB
SP = %x20
HTAB = %x09
